# Generated by Django 6.1.1 on 2026-09-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
