# Generated by Django 6.1.1 on 2026-09-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('course_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ClassSection',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_section_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='student',
            name='semester_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subject',
            name='course_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester_id',
            field=models.IntegerField(default=1),
        ),
    ]
