# Generated by Django 6.1.1 on 2026-09-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_semester_delete_classsection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester_id',
            field=models.IntegerField(),
        ),
    ]
