# Generated by Django 6.1.1 on 2026-09-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_student_semester_id_alter_subject_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_id',
            field=models.IntegerField(default=1),
        ),
    ]
